apiVersion: v1
kind: Service
metadata:
  name: os-api-service
spec:
  selector:
    app: os-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # For AWS Load Balancer
