apiVersion: v1
kind: ServiceAccount
metadata:
  name: os-sa
  namespace: default
  annotations:
    # This ARN allows the pod to assume the IAM role via OIDC (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::258531703731:role/os-api-irsa
