apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: stock-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # For AWS Load Balancer
