name: Deploy Stock API

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: techchallenge-cluster
  ECR_REPOSITORY: stock-api
  ACCOUNT_ID: 258531703731

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do c√≥digo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login no ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build & Push Stock API
      - name: Build & Push Stock API
        run: |
          ECR_REGISTRY=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Atualiza kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

      # Rollout restart Stock API
      - name: Rollout Stock API
        run: |
          kubectl rollout restart deployment stock-api -n default